name: Deploy Static Website to EC2

on:
  push:
    branches:
      - main  # Adjust the branch as per your workflow

jobs:
  deploy:
    runs-on: self-hosted  # Specify that the job runs on your self-hosted runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build and Deploy Docker Image
      run: |
        # Build the Docker image
        sudo docker build -t todolist .

        # Stop and remove the existing container if it's running
        sudo docker stop static-website
        sudo docker rm -f static-website

        # Run the new container
        docker run -d -p 80:80 --name static-website static-website:latest
