name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16' # Use the appropriate version if needed

    - name: Install dependencies
      run: npm install

    - name: Run lint
      run: npm run lint # Replace this with the lint command if you have a linting setup

    - name: Build project
      run: npm run build # Replace this with the build command if you have a build setup

    - name: Deploy
      run: echo "Deploy step - add deployment commands if needed"
